name: journal
description: A simple log writer and subscriber usable both from libraries and applications.
repository: https://github.com/skreborn/journal
version: 0.1.0+1

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.1.0
  js: ^0.6.5
  logging: ^1.0.0
  meta: ^1.9.1
  source_map_stack_trace: ^2.1.0
  source_maps: ^0.10.10
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^3.0.0
