name: journal
description: A simple log writer and subscriber usable both from libraries and applications.
repository: https://github.com/skreborn/journal
version: 0.3.0

environment:
  sdk: ^3.3.0

dependencies:
  ffi: ^2.1.4
  logging: ^1.3.0
  meta: ^1.16.0
  stack_trace: ^1.12.1
  web: ^1.1.1

dev_dependencies:
  lints: ^3.0.0
